#!/usr/bin/python3
# Monopole DFS solver for Dr. Ecco challenege
# by Merlin Carson

import sys
import time


# verifies and returns correct number of comman line arguments
def parse_args(args):

    if len(args) < 3:
        sys.exit("Usage: ./mono.py <num monopoles (<=52)> <num rooms>")

    return int(sys.argv[1]), int(sys.argv[2])

# Monopole constraining X + Y = Z
def is_additive(x, y, z):

    if (x + y == z):
        return True

    return False

# Monopole constraining, no room contains two monopoles that sum to a third
def place_mono(cur_monos, new_mono):

    # base case, not enough monopoles in room to be additive
    if len(cur_monos) < 2:
        return True

    for i, x in enumerate(cur_monos[:-1]):
        for y in cur_monos[i+1:]:
            if is_additive(x, y, new_mono) is True:
                return False
    return True

# verifies solution contains all monopoles 
def verify_all_monos(solution, num_monos):
    
    for mono in range(1, num_monos+1):
        for i, (_, values) in enumerate(solution.items(), start=1):
            if mono in values:
                break 
            if i == len(solution.keys()):
                return False

    return True

# verifies solution adhears to constraints
def verify_solution(solution, num_monos):

    # check to make sure all monopoles have been placed in rooms
    if not verify_all_monos(solution, num_monos):
        return None

    for key in solution.keys():
        # if there are less than 3 monopoles in a room, don't need to check if there is an additive combo
        if len(solution[key]) < 3:
            continue

        # check all combinations for additive combo
        for i, x in enumerate(solution[key][:-2]):
            for y in solution[key][i+1:-1]:
                for z in solution[key][i+2:]:
                    if is_additive(x, y, z) is True:
                        return None

    return solution

# Helper function for staring DFS recursion
def solver(num_monos, num_rooms):

    # lists of all possible monopoles and rooms
    monos = list(range(1,num_monos+1))
    monos.append(-1) # add stopping condition
    rooms = [str(i) for i in range(1, num_rooms+1)]

    # data struct for final solution set
    solution = {i: [] for i in rooms}

    return solve(monos, monos.pop(0), rooms, solution)

# Depth First Search with constraint function place_mono
def solve(monos, mono, rooms, solution):

    # base case
    if mono == -1:
        return solution

    # place monopole
    for room in rooms:
        if place_mono(solution[room], mono) is True:
            solution[room].append(mono)
            solution = solve(monos, monos.pop(0), rooms, solution)
            if len(monos) == 0:
                return solution
            solution[room].pop()

    monos.insert(0, mono)
    return solution
    
def show_results(solution):

    if solution is None:
        print('unsat')
    else:
        for i, key in enumerate(solution.keys()):
            for value in solution[key]:
                print(value, end=' ')
            print()

def main():

    # verify and load correct number of command line arguments
    num_monos, num_rooms = parse_args(sys.argv)

    # find solution to monopole problem using DFS
    solution = solver(num_monos, num_rooms)

    # verify the solution is correct
    solution = verify_solution(solution, num_monos)

    # print results to screen
    show_results(solution)

    return 0

if __name__ == '__main__':
    sys.exit(main())
